//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XAFWinFormsSample.Module.BusinessObjects.Database
{

    public partial class BRAND : XPLiteObject
    {
        int fID_BRAND;
        [Key(true)]
        public int ID_BRAND
        {
            get { return fID_BRAND; }
            set { SetPropertyValue<int>(nameof(ID_BRAND), ref fID_BRAND, value); }
        }
        SUPPLIER fID_SUPPLIER;
        [Association(@"BRANDReferencesSUPPLIER")]
        public SUPPLIER ID_SUPPLIER
        {
            get { return fID_SUPPLIER; }
            set { SetPropertyValue<SUPPLIER>(nameof(ID_SUPPLIER), ref fID_SUPPLIER, value); }
        }
        string fDSC_BRAND;
        [Indexed(Name = @"BRAND_I2", Unique = true)]
        [Size(40)]
        public string DSC_BRAND
        {
            get { return fDSC_BRAND; }
            set { SetPropertyValue<string>(nameof(DSC_BRAND), ref fDSC_BRAND, value); }
        }
        [Association(@"PRODUCTReferencesBRAND")]
        public XPCollection<PRODUCT> PRODUCTs { get { return GetCollection<PRODUCT>(nameof(PRODUCTs)); } }
    }

}
