//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XAFWinFormsSample.Module.BusinessObjects.Database
{

    public partial class CUSTOMER : XPLiteObject
    {
        int fID_CUSTOMER;
        [Key(true)]
        public int ID_CUSTOMER
        {
            get { return fID_CUSTOMER; }
            set { SetPropertyValue<int>(nameof(ID_CUSTOMER), ref fID_CUSTOMER, value); }
        }
        string fFIRST_NAME;
        [Indexed(Name = @"CUSTOMER_I1")]
        [Size(40)]
        public string FIRST_NAME
        {
            get { return fFIRST_NAME; }
            set { SetPropertyValue<string>(nameof(FIRST_NAME), ref fFIRST_NAME, value); }
        }
        string fLAST_NAME;
        [Indexed(Name = @"CUSTOMER_I2")]
        [Size(40)]
        public string LAST_NAME
        {
            get { return fLAST_NAME; }
            set { SetPropertyValue<string>(nameof(LAST_NAME), ref fLAST_NAME, value); }
        }
        string fMIDDLE_NAME;
        [Size(40)]
        public string MIDDLE_NAME
        {
            get { return fMIDDLE_NAME; }
            set { SetPropertyValue<string>(nameof(MIDDLE_NAME), ref fMIDDLE_NAME, value); }
        }
        string fSIN_NUMBER;
        [Size(40)]
        public string SIN_NUMBER
        {
            get { return fSIN_NUMBER; }
            set { SetPropertyValue<string>(nameof(SIN_NUMBER), ref fSIN_NUMBER, value); }
        }
        [Association(@"ORDERReferencesCUSTOMER")]
        public XPCollection<ORDER> ORDERs { get { return GetCollection<ORDER>(nameof(ORDERs)); } }
    }

}
