//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XAFWinFormsSample.Module.BusinessObjects.Database
{

    public partial class GROUP_PRODUCT : XPLiteObject
    {
        int fID_GROUP_PRODUCT;
        [Key(true)]
        public int ID_GROUP_PRODUCT
        {
            get { return fID_GROUP_PRODUCT; }
            set { SetPropertyValue<int>(nameof(ID_GROUP_PRODUCT), ref fID_GROUP_PRODUCT, value); }
        }
        string fDSC_GROUP_PRODUCT;
        [Indexed(Name = @"GROUP_PRODUCT_I1")]
        [Size(40)]
        public string DSC_GROUP_PRODUCT
        {
            get { return fDSC_GROUP_PRODUCT; }
            set { SetPropertyValue<string>(nameof(DSC_GROUP_PRODUCT), ref fDSC_GROUP_PRODUCT, value); }
        }
        [Association(@"SUBGROUP_PRODUCTReferencesGROUP_PRODUCT")]
        public XPCollection<SUBGROUP_PRODUCT> SUBGROUP_PRODUCTs { get { return GetCollection<SUBGROUP_PRODUCT>(nameof(SUBGROUP_PRODUCTs)); } }
    }

}
