//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XAFWinFormsSample.Module.BusinessObjects.Database
{

    public partial class KIND_OF_PACKING : XPLiteObject
    {
        int fID_KIND_OF_PACKING;
        [Key(true)]
        public int ID_KIND_OF_PACKING
        {
            get { return fID_KIND_OF_PACKING; }
            set { SetPropertyValue<int>(nameof(ID_KIND_OF_PACKING), ref fID_KIND_OF_PACKING, value); }
        }
        string fDSC_KIND_OF_PACKING;
        [Indexed(Name = @"KIND_OF_PACKING_I1")]
        [Size(40)]
        public string DSC_KIND_OF_PACKING
        {
            get { return fDSC_KIND_OF_PACKING; }
            set { SetPropertyValue<string>(nameof(DSC_KIND_OF_PACKING), ref fDSC_KIND_OF_PACKING, value); }
        }
        decimal fHEIGHT;
        public decimal HEIGHT
        {
            get { return fHEIGHT; }
            set { SetPropertyValue<decimal>(nameof(HEIGHT), ref fHEIGHT, value); }
        }
        decimal fWIDTH;
        public decimal WIDTH
        {
            get { return fWIDTH; }
            set { SetPropertyValue<decimal>(nameof(WIDTH), ref fWIDTH, value); }
        }
        decimal fDEPTH;
        public decimal DEPTH
        {
            get { return fDEPTH; }
            set { SetPropertyValue<decimal>(nameof(DEPTH), ref fDEPTH, value); }
        }
        decimal fWEIGHT;
        public decimal WEIGHT
        {
            get { return fWEIGHT; }
            set { SetPropertyValue<decimal>(nameof(WEIGHT), ref fWEIGHT, value); }
        }
        [Association(@"PRODUCTReferencesKIND_OF_PACKING")]
        public XPCollection<PRODUCT> PRODUCTs { get { return GetCollection<PRODUCT>(nameof(PRODUCTs)); } }
    }

}
