//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XAFWinFormsSample.Module.BusinessObjects.Database
{

    public partial class ORDER : XPLiteObject
    {
        int fID_ORDER;
        [Key(true)]
        public int ID_ORDER
        {
            get { return fID_ORDER; }
            set { SetPropertyValue<int>(nameof(ID_ORDER), ref fID_ORDER, value); }
        }
        CUSTOMER fID_CUSTOMER;
        [Association(@"ORDERReferencesCUSTOMER")]
        public CUSTOMER ID_CUSTOMER
        {
            get { return fID_CUSTOMER; }
            set { SetPropertyValue<CUSTOMER>(nameof(ID_CUSTOMER), ref fID_CUSTOMER, value); }
        }
        DateTime fDATE_ORDER;
        [Indexed(Name = @"ORDER_I2")]
        public DateTime DATE_ORDER
        {
            get { return fDATE_ORDER; }
            set { SetPropertyValue<DateTime>(nameof(DATE_ORDER), ref fDATE_ORDER, value); }
        }
        string fSTATUS;
        [Size(3)]
        public string STATUS
        {
            get { return fSTATUS; }
            set { SetPropertyValue<string>(nameof(STATUS), ref fSTATUS, value); }
        }
        DateTime fDATE_RELEASE;
        public DateTime DATE_RELEASE
        {
            get { return fDATE_RELEASE; }
            set { SetPropertyValue<DateTime>(nameof(DATE_RELEASE), ref fDATE_RELEASE, value); }
        }
        [Association(@"ORDER_ITEMReferencesORDER")]
        public XPCollection<ORDER_ITEM> ORDER_ITEMs { get { return GetCollection<ORDER_ITEM>(nameof(ORDER_ITEMs)); } }
    }

}
