//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XAFWinFormsSample.Module.BusinessObjects.Database
{

    public partial class ORDER_ITEM : XPLiteObject
    {
        int fID_ORDER_ITEM;
        [Key(true)]
        public int ID_ORDER_ITEM
        {
            get { return fID_ORDER_ITEM; }
            set { SetPropertyValue<int>(nameof(ID_ORDER_ITEM), ref fID_ORDER_ITEM, value); }
        }
        ORDER fID_ORDER;
        [Indexed(@"ID_PRODUCT", Name = @"ORDER_ITEM_I2", Unique = true)]
        [Association(@"ORDER_ITEMReferencesORDER")]
        public ORDER ID_ORDER
        {
            get { return fID_ORDER; }
            set { SetPropertyValue<ORDER>(nameof(ID_ORDER), ref fID_ORDER, value); }
        }
        PRODUCT fID_PRODUCT;
        [Association(@"ORDER_ITEMReferencesPRODUCT")]
        public PRODUCT ID_PRODUCT
        {
            get { return fID_PRODUCT; }
            set { SetPropertyValue<PRODUCT>(nameof(ID_PRODUCT), ref fID_PRODUCT, value); }
        }
        decimal fQUANTITY;
        public decimal QUANTITY
        {
            get { return fQUANTITY; }
            set { SetPropertyValue<decimal>(nameof(QUANTITY), ref fQUANTITY, value); }
        }
        decimal fPRICE_UNIT;
        public decimal PRICE_UNIT
        {
            get { return fPRICE_UNIT; }
            set { SetPropertyValue<decimal>(nameof(PRICE_UNIT), ref fPRICE_UNIT, value); }
        }
        decimal fSUBTOTAL;
        public decimal SUBTOTAL
        {
            get { return fSUBTOTAL; }
            set { SetPropertyValue<decimal>(nameof(SUBTOTAL), ref fSUBTOTAL, value); }
        }
    }

}
