//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XAFWinFormsSample.Module.BusinessObjects.Database
{

    public partial class PRICE : XPLiteObject
    {
        int fID_PRICE;
        [Key(true)]
        public int ID_PRICE
        {
            get { return fID_PRICE; }
            set { SetPropertyValue<int>(nameof(ID_PRICE), ref fID_PRICE, value); }
        }
        PRODUCT fID_PRODUCT;
        [Association(@"PRICEReferencesPRODUCT")]
        public PRODUCT ID_PRODUCT
        {
            get { return fID_PRODUCT; }
            set { SetPropertyValue<PRODUCT>(nameof(ID_PRODUCT), ref fID_PRODUCT, value); }
        }
        decimal fPRICE1;
        [Persistent(@"PRICE")]
        public decimal PRICE1
        {
            get { return fPRICE1; }
            set { SetPropertyValue<decimal>(nameof(PRICE1), ref fPRICE1, value); }
        }
        DateTime fDATE_EXPIRATION_PRICE;
        public DateTime DATE_EXPIRATION_PRICE
        {
            get { return fDATE_EXPIRATION_PRICE; }
            set { SetPropertyValue<DateTime>(nameof(DATE_EXPIRATION_PRICE), ref fDATE_EXPIRATION_PRICE, value); }
        }
    }

}
