//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XAFWinFormsSample.Module.BusinessObjects.Database
{

    public partial class PRODUCT : XPLiteObject
    {
        int fID_PRODUCT;
        [Key(true)]
        public int ID_PRODUCT
        {
            get { return fID_PRODUCT; }
            set { SetPropertyValue<int>(nameof(ID_PRODUCT), ref fID_PRODUCT, value); }
        }
        BRAND fID_BRAND;
        [Association(@"PRODUCTReferencesBRAND")]
        public BRAND ID_BRAND
        {
            get { return fID_BRAND; }
            set { SetPropertyValue<BRAND>(nameof(ID_BRAND), ref fID_BRAND, value); }
        }
        KIND_OF_PACKING fID_KIND_OF_PACKING;
        [Association(@"PRODUCTReferencesKIND_OF_PACKING")]
        public KIND_OF_PACKING ID_KIND_OF_PACKING
        {
            get { return fID_KIND_OF_PACKING; }
            set { SetPropertyValue<KIND_OF_PACKING>(nameof(ID_KIND_OF_PACKING), ref fID_KIND_OF_PACKING, value); }
        }
        string fEAN;
        [Indexed(Name = @"PRODUCT_I1")]
        [Size(13)]
        public string EAN
        {
            get { return fEAN; }
            set { SetPropertyValue<string>(nameof(EAN), ref fEAN, value); }
        }
        string fDSC_PRODUCT;
        [Indexed(Name = @"PRODUCT_I2")]
        [Size(80)]
        public string DSC_PRODUCT
        {
            get { return fDSC_PRODUCT; }
            set { SetPropertyValue<string>(nameof(DSC_PRODUCT), ref fDSC_PRODUCT, value); }
        }
        DateTime fDATE_REG_PRODUCT;
        public DateTime DATE_REG_PRODUCT
        {
            get { return fDATE_REG_PRODUCT; }
            set { SetPropertyValue<DateTime>(nameof(DATE_REG_PRODUCT), ref fDATE_REG_PRODUCT, value); }
        }
        [Association(@"ORDER_ITEMReferencesPRODUCT")]
        public XPCollection<ORDER_ITEM> ORDER_ITEMs { get { return GetCollection<ORDER_ITEM>(nameof(ORDER_ITEMs)); } }
        [Association(@"PRICEReferencesPRODUCT")]
        public XPCollection<PRICE> PRICEs { get { return GetCollection<PRICE>(nameof(PRICEs)); } }
    }

}
