//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XAFWinFormsSample.Module.BusinessObjects.Database
{

    public partial class SUBGROUP_PRODUCT : XPLiteObject
    {
        int fID_SUBGROUP_PRODUCT;
        [Key(true)]
        public int ID_SUBGROUP_PRODUCT
        {
            get { return fID_SUBGROUP_PRODUCT; }
            set { SetPropertyValue<int>(nameof(ID_SUBGROUP_PRODUCT), ref fID_SUBGROUP_PRODUCT, value); }
        }
        GROUP_PRODUCT fID_GROUP_PRODUCT;
        [Association(@"SUBGROUP_PRODUCTReferencesGROUP_PRODUCT")]
        public GROUP_PRODUCT ID_GROUP_PRODUCT
        {
            get { return fID_GROUP_PRODUCT; }
            set { SetPropertyValue<GROUP_PRODUCT>(nameof(ID_GROUP_PRODUCT), ref fID_GROUP_PRODUCT, value); }
        }
        string fDSC_SUBGROUP_PRODUCT;
        [Indexed(Name = @"SUBGROUP_PRODUCT_I2")]
        [Size(40)]
        public string DSC_SUBGROUP_PRODUCT
        {
            get { return fDSC_SUBGROUP_PRODUCT; }
            set { SetPropertyValue<string>(nameof(DSC_SUBGROUP_PRODUCT), ref fDSC_SUBGROUP_PRODUCT, value); }
        }
    }

}
