//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XAFWinFormsSample.Module.BusinessObjects.Database
{

    public partial class SUPPLIER : XPLiteObject
    {
        int fID_SUPPLIER;
        [Key(true)]
        public int ID_SUPPLIER
        {
            get { return fID_SUPPLIER; }
            set { SetPropertyValue<int>(nameof(ID_SUPPLIER), ref fID_SUPPLIER, value); }
        }
        string fDSC_SUPPLIER;
        [Indexed(Name = @"SUPPLIER_I1")]
        [Size(80)]
        public string DSC_SUPPLIER
        {
            get { return fDSC_SUPPLIER; }
            set { SetPropertyValue<string>(nameof(DSC_SUPPLIER), ref fDSC_SUPPLIER, value); }
        }
        DateTime fDATE_OF_REGISTER;
        public DateTime DATE_OF_REGISTER
        {
            get { return fDATE_OF_REGISTER; }
            set { SetPropertyValue<DateTime>(nameof(DATE_OF_REGISTER), ref fDATE_OF_REGISTER, value); }
        }
        [Association(@"BRANDReferencesSUPPLIER")]
        public XPCollection<BRAND> BRANDs { get { return GetCollection<BRAND>(nameof(BRANDs)); } }
    }

}
